version: "3.8"

services:
  training-express-app:
    container_name: training-express-app
    image: training-express-app
    restart: always
    environment:
      SOME_VAR: ${SOME_VAR}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
#    ports:
#      - ${API_PORT}:${API_PORT}
    networks:
      - training-express

networks:
  training-express:
    name: training-express
